install_packages:
  stage: install
  script:
    - npm install
    - npm run build:css
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
  only:
    refs:
      - natours-dev
    changes:
      - package.json
